### ISSUE TITLE
npm install fails - ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by ltglss** [Microsoft/BusinessPlatformApps#1160]
When running npm install within the Source/Site/Microsoft.Deployment.Site.Web directory, I get errors apparently when trying to install jspm:

> bpst@1.0.0 jspm-install C:\Users\IeT\source\repos\ltglss\BusinessPlatformApps\Source\Site\Microsoft.Deployment.Site.Web
> jspm install --log err -y

Configuration file wwwroot\config.js doesn't exist, create it?:Yes

err  TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
         at Function.from (buffer.js:225:9)
         at new Buffer (buffer.js:175:17)

I'm running node version v11.13.0, also tried with older versions with no luck.

Any idea what's causing this ?

**Comment by ltglss** [comment]
running "jspm registry config github" and configuring github credentials solved the issue

**Comment by ltglss** [comment]
running "jspm registry config github" and configuring github credentials solved the issue
